id: P84A8E91D
initial_creation_type: input
source_metadata:
  title: Menlungpa Mikyö Dorje
  language: bo
  description: 'Texts by and about Menlungpa Mikyö Dorje (sman lung pa mi bskyod rdo
    rje, b. 12th C.):'
  volume:
    6dcbb1847a6e4425816b93f35eb6184d:
      title: Prayer to the Indian Mahāpaṇḍita Padmasambhava
      parent: Prayers
created_at: '2022-03-01T00:45:15.178348'
last_modified_at: '2022-03-01T00:45:15.178351'
